[book]
title = "actix-web 中文文档 - Rust-Web 开发指南"
authors = ["zzy"]
language = "zh"
description = "Rust Web 框架, actix-web 开发指南, actix-web 项目实战, actix-web 中文文档"
src = "src"
multilingual = true

[output.html]
theme = "theme"
# default-theme = "rust"
git-repository-url = "https://github.com/zzy/actix-web-zh-cn"
curly-quotes = true
mathjax-support = true

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
